import type { ResolvedInstance } from "../types.ts";

/**
 * Generate /workspace/AGENTS.md — the environment self-awareness document.
 *
 * This file is baked into the Docker image at build time and loaded by
 * OpenCode via the `instructions` config field. It tells the AI agent
 * everything it needs to know about its sandbox environment:
 *
 *   - What OS / base image it's running on
 *   - What software is installed (derived from Docker config + install steps)
 *   - What MCP tool servers are available and what they do
 *   - What daemon services are running
 *   - What environment variables are set
 *   - What projects are mounted and where
 *   - How to bootstrap new projects
 *
 * The entire document is auto-generated from the ResolvedInstance — no
 * manual prose is needed. Templates contribute structured data (install
 * steps with descriptions, MCP servers, services) and this generator
 * converts that into a readable markdown document.
 */
export function generateAgentsMd(instance: ResolvedInstance): string {
  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push(`# Sandbox Environment — ${instance.name}`);
  lines.push(``);
  lines.push(`> Auto-generated by remote-opencode-sandbox. Do not edit manually.`);
  lines.push(`> Regenerate with: \`sandbox build\``);
  lines.push(``);
  lines.push(`You are running inside a Docker container managed by remote-opencode-sandbox.`);
  lines.push(`This document describes your environment so you can work effectively without`);
  lines.push(`needing to probe the system. Read it carefully.`);
  lines.push(``);

  // ── Base System ─────────────────────────────────────────────────────────
  lines.push(`## Base System`);
  lines.push(``);
  lines.push(`- **Image**: \`${instance.docker.baseImage}\``);
  lines.push(`- **User**: \`coder\` (UID 1000, non-root)`);
  lines.push(`- **Workspace**: \`/workspace\``);
  lines.push(`- **Shell**: bash`);
  lines.push(``);

  // ── Git Authentication ───────────────────────────────────────────────────
  lines.push(`## Git Authentication`);
  lines.push(``);
  lines.push(`This container uses **HTTPS with GitHub PATs** (Personal Access Tokens)`);
  lines.push(`for all git operations — **not SSH keys**. Authentication is handled`);
  lines.push(`automatically via git credential helpers.`);
  lines.push(``);
  lines.push(`### How it works`);
  lines.push(``);
  lines.push(`- A **default PAT** provides access to create repos, push to any repo`);
  lines.push(`  the token owner has access to, and perform \`gh\` CLI operations.`);
  lines.push(`- **Per-project PATs** are scoped to specific projects and override the`);
  lines.push(`  default when you \`git push\`/\`pull\` from within those project directories.`);
  lines.push(`- Credential routing is automatic via \`git config includeIf\` — you do not`);
  lines.push(`  need to configure anything manually.`);
  lines.push(``);
  lines.push(`### What to use`);
  lines.push(``);
  lines.push(`- **Always use HTTPS URLs** for git remotes, not SSH.`);
  lines.push(`  - Correct: \`https://github.com/org/repo.git\``);
  lines.push(`  - Wrong: \`git@github.com:org/repo.git\``);
  lines.push(`- \`git clone\`, \`git push\`, \`git pull\` — credentials are injected automatically.`);
  lines.push(`- \`gh repo create\`, \`gh pr create\`, etc. — the \`gh\` CLI is authenticated via`);
  lines.push(`  the \`GH_TOKEN\` env var (set to the default PAT).`);
  lines.push(``);
  lines.push(`### Creating new repositories`);
  lines.push(``);
  lines.push(`You can create repos directly:`);
  lines.push(`\`\`\`bash`);
  lines.push(`gh repo create <org>/<name> --private`);
  lines.push(`cd /workspace && git clone https://github.com/<org>/<name>.git`);
  lines.push(`\`\`\``);
  lines.push(``);
  lines.push(`The default PAT has \`repo\` scope so this works out of the box. After`);
  lines.push(`creating a repo, tell the user so they can optionally add it as a`);
  lines.push(`managed project via \`sandbox add\` on the host.`);
  lines.push(``);

  // ── Installed Software ──────────────────────────────────────────────────
  lines.push(`## Installed Software`);
  lines.push(``);

  // Common software from boolean flags
  lines.push(`| Software | Installed | Path / Notes |`);
  lines.push(`|----------|-----------|--------------|`);
  lines.push(`| Node.js | Yes | From base image |`);
  lines.push(`| npm | Yes | From base image |`);
  lines.push(`| Git | Yes | \`/usr/bin/git\` |`);
  lines.push(`| GitHub CLI | Yes | \`/usr/bin/gh\` |`);
  lines.push(
    `| Bun | ${instance.docker.installBun ? "Yes" : "No"} | ${instance.docker.installBun ? "`~/.bun/bin/bun`" : "Not installed"} |`
  );
  lines.push(
    `| Google Chrome | ${instance.docker.installChrome ? "Yes" : "No"} | ${instance.docker.installChrome ? "`/usr/bin/google-chrome-stable` — use with `--no-sandbox --headless`" : "Not installed"} |`
  );
  lines.push(
    `| Supabase CLI | ${instance.docker.installSupabaseCli ? "Yes" : "No"} | ${instance.docker.installSupabaseCli ? "`/usr/local/bin/supabase`" : "Not installed"} |`
  );

  // Custom install steps
  const installSteps = instance.docker.installSteps ?? [];
  for (const step of installSteps) {
    const label = step.comment ?? step.name;
    const desc = step.description ?? "Custom install step";
    lines.push(`| ${label} | Yes | ${desc} |`);
  }

  lines.push(``);

  // Detailed descriptions for install steps that have them
  const stepsWithDescriptions = installSteps.filter((s) => s.description);
  if (stepsWithDescriptions.length > 0) {
    lines.push(`### Custom Software Details`);
    lines.push(``);
    for (const step of stepsWithDescriptions) {
      lines.push(`#### ${step.comment ?? step.name}`);
      lines.push(``);
      lines.push(step.description!);
      lines.push(``);
    }
  }

  // ── MCP Tool Servers ────────────────────────────────────────────────────
  const mcpEntries = Object.entries(instance.mcp);
  if (mcpEntries.length > 0) {
    lines.push(`## MCP Tool Servers`);
    lines.push(``);
    lines.push(
      `These MCP servers are configured and available to you. They provide`
    );
    lines.push(
      `specialized tools beyond your built-in capabilities. Use them when relevant.`
    );
    lines.push(``);

    for (const [name, server] of mcpEntries) {
      const type = server.type === "remote" ? "Remote" : "Local";
      const target =
        server.type === "remote"
          ? server.url
          : server.command?.join(" ");
      lines.push(`### \`${name}\` (${type})`);
      lines.push(``);
      lines.push(`- **Type**: ${type}`);
      if (target) {
        lines.push(`- **Endpoint**: \`${target}\``);
      }
      if (server.environment && Object.keys(server.environment).length > 0) {
        lines.push(`- **Environment**:`);
        for (const [k, v] of Object.entries(server.environment)) {
          lines.push(`  - \`${k}=${v}\``);
        }
      }
      if (server.enabled === false) {
        lines.push(`- **Status**: Disabled`);
      }
      lines.push(``);
    }
  }

  // ── Running Services ────────────────────────────────────────────────────
  const daemons = instance.allContainerServices.filter(
    (s) => s.type === "daemon"
  );
  const oneshots = instance.allContainerServices.filter(
    (s) => s.type === "oneshot"
  );

  if (daemons.length > 0 || oneshots.length > 0) {
    lines.push(`## Container Services`);
    lines.push(``);

    if (daemons.length > 0) {
      lines.push(`### Daemon Services (always running)`);
      lines.push(``);
      for (const svc of daemons) {
        lines.push(`- **${svc.name}**: \`${svc.command}\``);
        if (svc.workdir) {
          lines.push(`  - Working directory: \`${svc.workdir}\``);
        }
        if (svc.port) {
          lines.push(`  - Port: ${svc.port}`);
        }
        if (svc.env && Object.keys(svc.env).length > 0) {
          lines.push(
            `  - Env: ${Object.entries(svc.env)
              .map(([k, v]) => `\`${k}=${v}\``)
              .join(", ")}`
          );
        }
      }
      lines.push(``);
    }

    if (oneshots.length > 0) {
      lines.push(`### Oneshot Services (run at startup)`);
      lines.push(``);
      for (const svc of oneshots) {
        lines.push(`- **${svc.name}**: \`${svc.command}\``);
        if (svc.workdir) {
          lines.push(`  - Working directory: \`${svc.workdir}\``);
        }
      }
      lines.push(``);
    }
  }

  // ── Environment Variables ───────────────────────────────────────────────
  if (Object.keys(instance.envOverrides).length > 0) {
    lines.push(`## Environment Variables`);
    lines.push(``);
    lines.push(
      `These environment variables are set in the container and available`
    );
    lines.push(`to all processes:`);
    lines.push(``);
    for (const [key, value] of Object.entries(instance.envOverrides)) {
      lines.push(`- \`${key}=${value}\``);
    }
    lines.push(``);
  }

  // ── Projects ────────────────────────────────────────────────────────────
  if (instance.projects.length > 0) {
    lines.push(`## Projects`);
    lines.push(``);
    lines.push(`The following projects are mounted in this container:`);
    lines.push(``);

    for (const proj of instance.projects) {
      lines.push(`### ${proj.name}`);
      lines.push(``);
      lines.push(`- **Path**: \`${proj.workspacePath}\``);
      if (Object.keys(proj.envOverrides).length > 0) {
        lines.push(`- **Env overrides**:`);
        for (const [k, v] of Object.entries(proj.envOverrides)) {
          lines.push(`  - \`${k}=${v}\``);
        }
      }
      lines.push(``);
    }
  }

  // ── Extra Repositories ───────────────────────────────────────────────────
  if (instance.extraRepos.length > 0) {
    lines.push(`## Extra Repositories`);
    lines.push(``);
    lines.push(`These repositories are cloned into \`/workspace/\` at container startup`);
    lines.push(`and pulled on subsequent restarts. They are not host-mounted — changes`);
    lines.push(`persist inside the container volume.`);
    lines.push(``);

    for (const repoUrl of instance.extraRepos) {
      const repoName = repoUrl.replace(/\.git$/, "").split("/").pop() ?? "unknown";
      const isSsh = repoUrl.startsWith("git@");
      const authMethod = isSsh ? "SSH key" : "PAT (HTTPS)";
      lines.push(`- **${repoName}**: \`/workspace/${repoName}\``);
      lines.push(`  - Source: \`${repoUrl}\``);
      lines.push(`  - Auth: ${authMethod}`);
    }
    lines.push(``);
  }

  // ── Port Mappings ───────────────────────────────────────────────────────
  if (instance.ports.length > 0) {
    lines.push(`## Port Mappings`);
    lines.push(``);
    for (const port of instance.ports) {
      lines.push(`- \`${port}\``);
    }
    lines.push(``);
  }

  // ── Networking ──────────────────────────────────────────────────────────
  lines.push(`## Networking`);
  lines.push(``);
  lines.push(
    `- To reach services running on the **host machine**, use \`host.docker.internal\``
  );
  lines.push(`  instead of \`localhost\` or \`127.0.0.1\`.`);
  lines.push(
    `- Example: a Supabase instance on the host at port 54321 is reachable at`
  );
  lines.push(`  \`http://host.docker.internal:54321\`.`);
  lines.push(``);

  // ── Bootstrapping New Projects ──────────────────────────────────────────
  lines.push(`## Bootstrapping New Projects`);
  lines.push(``);
  lines.push(
    `You can create new projects in \`/workspace\`. The container has the`
  );
  lines.push(`following tools available for project initialization:`);
  lines.push(``);

  if (instance.docker.installBun) {
    lines.push(`- \`bun init\` / \`bun create\` — scaffold Node/TypeScript projects`);
  }
  lines.push(`- \`npm init\` / \`npx create-*\` — scaffold via npm`);
  lines.push(`- \`git clone\` — clone existing repositories`);

  // List capabilities from install steps
  for (const step of installSteps) {
    if (step.name === "godot") {
      lines.push(
        `- \`godot\` — create Godot game projects (binary at \`${instance.envOverrides.GODOT_PATH ?? "/usr/local/bin/godot"}\`)`
      );
    }
  }
  lines.push(``);

  lines.push(
    `When bootstrapping a new project, create it under \`/workspace/<project-name>/\`.`
  );
  lines.push(
    `If the project needs MCP tools you don't currently have, tell the user what`
  );
  lines.push(
    `MCP servers or software would be useful and they can configure them via`
  );
  lines.push(`\`sandbox build\`.`);
  lines.push(``);

  // ── Permissions ─────────────────────────────────────────────────────────
  lines.push(`## Permissions`);
  lines.push(``);
  lines.push(
    `Your permission level is \`${instance.permission}\`. ${instance.permission === "allow" ? "You can make changes without asking for approval." : "You must ask the user before making changes."}`
  );
  lines.push(``);

  return lines.join("\n");
}
