import os from "node:os";
import type { ResolvedInstance } from "../types.ts";

/**
 * Generate docker-compose.yml content for a sandbox instance.
 *
 * Uses YAML string building (not the yaml library) for precise control
 * over formatting and comments.
 */
export function generateCompose(instance: ResolvedInstance): string {
  const lines: string[] = [];
  const home = os.homedir();

  lines.push(`# Auto-generated by remote-opencode-sandbox`);
  lines.push(`# Instance: ${instance.name}`);
  lines.push(`# Projects: ${instance.projects.map((p) => p.name).join(", ")}`);
  lines.push(`# DO NOT EDIT — regenerate with: sandbox build`);
  lines.push(``);
  lines.push(`services:`);
  lines.push(`  sandbox:`);
  lines.push(`    build:`);
  lines.push(`      context: .`);
  lines.push(`      dockerfile: Dockerfile`);
  lines.push(`    container_name: sandbox-${instance.name}`);
  lines.push(`    stdin_open: true`);
  lines.push(`    tty: true`);
  lines.push(`    restart: unless-stopped`);
  lines.push(``);

  // ── Env file (secrets) ───────────────────────────────────────────
  lines.push(`    # Secrets (GH_TOKEN, git identity, etc.)`);
  lines.push(`    env_file:`);
  lines.push(`      - .env`);
  lines.push(``);

  // ── Port mappings ────────────────────────────────────────────────
  if (instance.ports.length > 0) {
    lines.push(`    # Port mappings`);
    lines.push(`    ports:`);
    for (const port of instance.ports) {
      lines.push(`      - "${port}"`);
    }
    lines.push(``);
  }

  // ── Host networking ──────────────────────────────────────────────
  lines.push(`    # Allow container to reach host services via host.docker.internal`);
  lines.push(`    extra_hosts:`);
  lines.push(`      - "host.docker.internal:host-gateway"`);
  lines.push(``);

  // ── Volumes ──────────────────────────────────────────────────────
  lines.push(`    volumes:`);

  // Project bind mounts
  for (const proj of instance.projects) {
    lines.push(`      # Project: ${proj.name}`);
    lines.push(`      - ${proj.hostPath}:${proj.workspacePath}`);
  }
  lines.push(``);

  // Named volumes for node_modules per project
  const nodeModulesVolumes: string[] = [];
  for (const proj of instance.projects) {
    const volName = `${proj.name}-node-modules`;
    nodeModulesVolumes.push(volName);
    lines.push(`      # node_modules for ${proj.name}`);
    lines.push(`      - ${volName}:${proj.workspacePath}/node_modules`);
  }
  lines.push(``);

  // OpenCode container config (read-only — regenerated by `sandbox build`)
  lines.push(`      # OpenCode container config (permission, MCPs)`);
  lines.push(`      - ./opencode.docker.json:/home/coder/.sandbox/opencode.docker.json:ro`);
  lines.push(``);

  // Git credentials (per-project PATs via includeIf)
  lines.push(`      # Git credentials (per-project PATs, read-only)`);
  lines.push(`      - ./git-credentials:/home/coder/.git-credentials:ro`);
  lines.push(``);

  // remote-opencode config (read-write)
  lines.push(`      # remote-opencode config + data (read-write)`);
  lines.push(`      - \${HOME}/.remote-opencode:/home/coder/.remote-opencode`);
  lines.push(``);

  // OpenCode auth and session data (read-write for token refresh)
  lines.push(`      # OpenCode auth tokens and session data`);
  lines.push(`      - \${HOME}/.local/share/opencode:/home/coder/.local/share/opencode`);
  lines.push(``);

  // SSH keys (read-only, if configured)
  if (instance.ssh?.keyPath) {
    const keyPath = instance.ssh.keyPath;
    lines.push(`      # SSH key for git authentication (read-only)`);
    lines.push(`      - ${keyPath}:/home/coder/.ssh/id_key:ro`);
    // Also mount the public key if it exists (some git hosts need it)
    lines.push(`      - ${keyPath}.pub:/home/coder/.ssh/id_key.pub:ro`);
    lines.push(``);
  }

  // ── Environment overrides ────────────────────────────────────────
  lines.push(`    environment:`);

  // OpenCode config path
  lines.push(`      # Container-specific OpenCode config (permission: allow, container MCPs)`);
  lines.push(`      - OPENCODE_CONFIG=/home/coder/.sandbox/opencode.docker.json`);
  lines.push(``);

  // Chrome env vars
  if (instance.docker.installChrome) {
    lines.push(`      # Google Chrome`);
    lines.push(`      - CHROME_PATH=/usr/bin/google-chrome-stable`);
    lines.push(`      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable`);
    lines.push(`      - CHROME_FLAGS=--no-sandbox --disable-gpu --disable-dev-shm-usage`);
    lines.push(`      - PUPPETEER_ARGS=--no-sandbox --disable-gpu --disable-dev-shm-usage`);
    lines.push(``);
  }

  // Env overrides from all projects
  if (Object.keys(instance.envOverrides).length > 0) {
    lines.push(`      # Env var overrides (localhost → host.docker.internal)`);
    for (const [key, value] of Object.entries(instance.envOverrides)) {
      lines.push(`      - ${key}=${value}`);
    }
    lines.push(``);
  }

  // ── Security hardening ───────────────────────────────────────────
  lines.push(`    # Security hardening`);
  lines.push(`    security_opt:`);
  lines.push(`      - no-new-privileges:true`);
  lines.push(`    cap_drop:`);
  lines.push(`      - ALL`);
  lines.push(`    cap_add:`);
  lines.push(`      - CHOWN`);
  lines.push(`      - DAC_OVERRIDE`);
  lines.push(`      - FOWNER`);
  lines.push(`      - SETGID`);
  lines.push(`      - SETUID`);
  if (instance.docker.installChrome) {
    lines.push(`      - SYS_ADMIN  # Required for Chrome sandbox`);
  }
  lines.push(`    read_only: false`);
  lines.push(``);

  // ── tmpfs ────────────────────────────────────────────────────────
  lines.push(`    # tmpfs for Chrome and temp files`);
  lines.push(`    tmpfs:`);
  lines.push(`      - /tmp:size=512M`);
  lines.push(`      - /run:size=64M`);
  lines.push(``);

  // ── Named volumes ───────────────────────────────────────────────
  if (nodeModulesVolumes.length > 0) {
    lines.push(`volumes:`);
    for (const vol of nodeModulesVolumes) {
      lines.push(`  ${vol}:`);
    }
  }

  return lines.join("\n") + "\n";
}
