import type { DockerInstallStep, ResolvedInstance } from "../types.ts";

/**
 * Chrome dependency libraries required for headless Chrome in containers.
 * The .deb installer *should* pull these in, but explicitly listing them
 * guarantees they're present in all environments.
 */
const CHROME_DEPS = [
  "fonts-liberation",
  "libnss3",
  "libatk-bridge2.0-0",
  "libdrm2",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libgbm1",
  "libpango-1.0-0",
  "libcairo2",
  "libcups2",
  "libxss1",
  "libxtst6",
  "xdg-utils",
];

/**
 * Generate Dockerfile content for a sandbox instance.
 *
 * Based on a proven Docker sandbox setup,
 * generalized for any project configuration.
 */
export function generateDockerfile(instance: ResolvedInstance): string {
  const { docker } = instance;
  const lines: string[] = [];

  lines.push(`# Auto-generated by remote-opencode-sandbox`);
  lines.push(`# Instance: ${instance.name}`);
  lines.push(`# DO NOT EDIT — regenerate with: sandbox build`);
  lines.push(``);
  lines.push(`FROM ${docker.baseImage}`);
  lines.push(``);

  // Collect apt packages from custom install steps
  const installSteps: DockerInstallStep[] = docker.installSteps ?? [];
  const stepAptPackages = installSteps.flatMap((s) => s.aptPackages ?? []);

  // ── System packages ──────────────────────────────────────────────
  lines.push(`# System packages`);
  const packages = [
    "git",
    "curl",
    "wget",
    "unzip",
    "jq",
    "ca-certificates",
    "gnupg",
    "openssh-client",
    // Chrome dependency libraries (explicit for reliability)
    ...(docker.installChrome ? CHROME_DEPS : []),
    ...docker.extraPackages,
    // Packages required by custom install steps
    ...stepAptPackages,
  ];
  lines.push(`RUN apt-get update && apt-get install -y --no-install-recommends \\`);
  lines.push(`    ${packages.join(" \\\n    ")} \\`);
  lines.push(`    && rm -rf /var/lib/apt/lists/*`);
  lines.push(``);

  // ── Google Chrome (if needed) ────────────────────────────────────
  if (docker.installChrome) {
    lines.push(`# Google Chrome (for MCP browser tools)`);
    lines.push(`RUN wget -q -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \\`);
    lines.push(`    && apt-get update \\`);
    lines.push(`    && apt-get install -y /tmp/google-chrome.deb \\`);
    lines.push(`    && rm -f /tmp/google-chrome.deb \\`);
    lines.push(`    && rm -rf /var/lib/apt/lists/*`);
    lines.push(``);

    // Chrome env vars at build time (also set in compose, but having them
    // in the image means manual `docker run` also works)
    lines.push(`# Chrome flags for running in container`);
    lines.push(`ENV CHROME_PATH=/usr/bin/google-chrome-stable`);
    lines.push(`ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable`);
    lines.push(`ENV CHROME_FLAGS="--no-sandbox --disable-gpu --disable-dev-shm-usage"`);
    lines.push(``);
  }

  // ── Create non-root user ─────────────────────────────────────────
  // node:24-bookworm already has a 'node' user with UID 1000.
  // Rename it to 'coder' for clarity.
  lines.push(`# Create non-root user (rename node→coder, UID/GID 1000)`);
  lines.push(`RUN usermod -l coder -d /home/coder -m node \\`);
  lines.push(`    && groupmod -n coder node`);
  lines.push(``);

  // ── GitHub CLI ───────────────────────────────────────────────────
  lines.push(`# GitHub CLI`);
  lines.push(`RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \\`);
  lines.push(`    | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \\`);
  lines.push(`    && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \\`);
  lines.push(`    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list \\`);
  lines.push(`    && apt-get update && apt-get install -y gh \\`);
  lines.push(`    && rm -rf /var/lib/apt/lists/*`);
  lines.push(``);

  // ── Supabase CLI (if needed) ─────────────────────────────────────
  if (docker.installSupabaseCli) {
    lines.push(`# Supabase CLI`);
    lines.push(`RUN curl -fsSL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz \\`);
    lines.push(`    | tar xz -C /usr/local/bin supabase`);
    lines.push(``);
  }

  // ── Custom install steps (from templates / .sandbox.json) ────────
  // Root-context steps first, then coder-context steps.
  const rootSteps = installSteps.filter((s) => (s.user ?? "root") === "root");
  const coderSteps = installSteps.filter((s) => s.user === "coder");

  for (const step of rootSteps) {
    lines.push(`# ${step.comment ?? step.name}`);
    for (const line of step.instructions) {
      lines.push(line);
    }
    lines.push(``);
  }

  if (coderSteps.length > 0) {
    lines.push(`USER coder`);
    for (const step of coderSteps) {
      lines.push(`# ${step.comment ?? step.name}`);
      for (const line of step.instructions) {
        lines.push(line);
      }
      lines.push(``);
    }
    lines.push(`USER root`);
    lines.push(``);
  }

  // ── OpenCode (installed as root for clean global placement) ──────
  lines.push(`# OpenCode`);
  lines.push(`RUN curl -fsSL https://opencode.ai/install | bash \\`);
  lines.push(`    && mv /root/.opencode/bin/opencode /usr/local/bin/opencode \\`);
  lines.push(`    && chmod 755 /usr/local/bin/opencode \\`);
  lines.push(`    && rm -rf /root/.opencode`);
  lines.push(``);

  // ── remote-opencode ──────────────────────────────────────────────
  lines.push(`# remote-opencode (Discord bridge)`);
  lines.push(`RUN npm install -g remote-opencode@latest`);
  lines.push(``);

  // ── Bun (installed as coder user) ────────────────────────────────
  if (docker.installBun) {
    lines.push(`# Bun (install for coder user)`);
    lines.push(`USER coder`);
    lines.push(`RUN curl -fsSL https://bun.sh/install | bash`);
    lines.push(`ENV PATH="/home/coder/.bun/bin:$PATH"`);
    lines.push(`USER root`);
    lines.push(``);
  }

  // ── Workspace and directory setup ─────────────────────────────────
  lines.push(`# Workspace — projects are mounted here`);
  lines.push(`RUN mkdir -p /workspace`);

  // Pre-create node_modules dirs for each project that uses node
  for (const proj of instance.projects) {
    lines.push(
      `RUN mkdir -p ${proj.workspacePath}/node_modules`
    );
  }

  // chown AFTER all dirs are created, so named volumes inherit coder ownership
  lines.push(`RUN chown -R coder:coder /workspace`);
  lines.push(``);

  // Create directories for config/data mounts (so Docker doesn't create them as root)
  lines.push(`# Pre-create directories for volume mounts`);
  lines.push(`RUN mkdir -p /home/coder/.config/opencode \\`);
  lines.push(`    && mkdir -p /home/coder/.local/share/opencode \\`);
  lines.push(`    && mkdir -p /home/coder/.remote-opencode \\`);
  lines.push(`    && mkdir -p /home/coder/.git-credentials \\`);
  lines.push(`    && mkdir -p /home/coder/.ssh \\`);
  lines.push(`    && chmod 700 /home/coder/.ssh \\`);
  lines.push(`    && chown -R coder:coder /home/coder/.config /home/coder/.local /home/coder/.remote-opencode /home/coder/.git-credentials /home/coder/.ssh`);
  lines.push(``);

  // Copy opencode.docker.json into the image as fallback
  // (also mounted via compose volume for easy updates without rebuild)
  lines.push(`# OpenCode container config (permission + MCPs)`);
  lines.push(`COPY --chown=coder:coder opencode.docker.json /home/coder/.config/opencode/opencode.json`);
  lines.push(``);

  // Copy workspace AGENTS.md so the bot knows about its environment
  lines.push(`# Workspace instructions (auto-generated environment docs for the AI agent)`);
  lines.push(`COPY --chown=coder:coder AGENTS.md /workspace/AGENTS.md`);
  lines.push(``);

  // ── Entrypoint ───────────────────────────────────────────────────
  lines.push(`# Entrypoint (process supervisor)`);
  lines.push(`COPY --chown=coder:coder docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh`);
  lines.push(`RUN chmod +x /usr/local/bin/docker-entrypoint.sh`);
  lines.push(``);

  // ── Switch to non-root user ──────────────────────────────────────
  lines.push(`USER coder`);
  lines.push(``);

  // ── Git config ──────────────────────────────────────────────────
  // The credential.helper is set via includeIf in the mounted gitconfig.sandbox
  // file, which routes PATs per-project based on working directory.
  // gh CLI uses GH_TOKEN env var directly (set in .env via env_file).
  lines.push(`# Git defaults (safe, sensible)`);
  lines.push(`RUN git config --global push.default simple \\`);
  lines.push(`    && git config --global push.autoSetupRemote true \\`);
  lines.push(`    && git config --global include.path /home/coder/.git-credentials/gitconfig.sandbox`);
  lines.push(``);

  lines.push(`WORKDIR /workspace`);
  lines.push(`ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]`);

  return lines.join("\n") + "\n";
}
