import type { ResolvedInstance } from "../types.ts";
import {
  WATCHDOG_INTERVAL,
  RESTART_DELAY,
  MAX_RAPID_RESTARTS,
  RAPID_WINDOW,
  BACKOFF_DELAY,
} from "../constants.ts";

/**
 * Generate docker-entrypoint.sh — the process supervisor.
 *
 * This is a generalized process supervisor for sandbox containers.
 * It handles:
 *   - Dependency resolution (topological sort)
 *   - Oneshot services (run once, must succeed)
 *   - Daemon services (long-running, monitored by watchdog)
 *   - Log prefixing per service
 *   - Graceful shutdown on SIGTERM/SIGINT
 *   - Crash-loop backoff for daemons
 */
export function generateEntrypoint(instance: ResolvedInstance): string {
  const containerServices = instance.allContainerServices;

  // Separate oneshots and daemons
  const oneshots = containerServices.filter((s) => s.type === "oneshot");
  const daemons = containerServices.filter((s) => s.type === "daemon");

  const lines: string[] = [];

  lines.push(`#!/usr/bin/env bash`);
  lines.push(`# Auto-generated by remote-opencode-sandbox`);
  lines.push(`# Instance: ${instance.name}`);
  lines.push(`# DO NOT EDIT — regenerate with: sandbox build`);
  lines.push(`#`);
  lines.push(`# Process supervisor for ${containerServices.length} services:`);
  for (const svc of containerServices) {
    const deps = svc.dependsOn?.length ? ` (depends: ${svc.dependsOn.join(", ")})` : "";
    lines.push(`#   [${svc.type}] ${svc.name}${deps}`);
  }
  lines.push(`set -euo pipefail`);
  lines.push(``);

  // ── Configuration ────────────────────────────────────────────────
  lines.push(`# ── Watchdog configuration ──`);
  lines.push(`WATCHDOG_INTERVAL=${WATCHDOG_INTERVAL}`);
  lines.push(`RESTART_DELAY=${RESTART_DELAY}`);
  lines.push(`MAX_RAPID_RESTARTS=${MAX_RAPID_RESTARTS}`);
  lines.push(`RAPID_WINDOW=${RAPID_WINDOW}`);
  lines.push(`BACKOFF_DELAY=${BACKOFF_DELAY}`);
  lines.push(``);

  // ── State ────────────────────────────────────────────────────────
  lines.push(`# ── State ──`);
  lines.push(`SHUTTING_DOWN=false`);
  lines.push(`declare -A DAEMON_PIDS`);
  lines.push(`declare -A RESTART_COUNTS`);
  lines.push(`declare -A LAST_RESTART_TIMES`);
  lines.push(``);

  // ── Logging helper ───────────────────────────────────────────────
  lines.push(`# ── Logging ──`);
  lines.push(`log() { echo "[sandbox:$1] $2"; }`);
  lines.push(``);

  // ── Signal trap ──────────────────────────────────────────────────
  lines.push(`# ── Graceful shutdown ──`);
  lines.push(`cleanup() {`);
  lines.push(`  SHUTTING_DOWN=true`);
  lines.push(`  log "supervisor" "Shutting down all services..."`);
  lines.push(`  for name in "\${!DAEMON_PIDS[@]}"; do`);
  lines.push(`    local pid=\${DAEMON_PIDS[$name]}`);
  lines.push(`    if kill -0 "$pid" 2>/dev/null; then`);
  lines.push(`      log "$name" "Stopping (PID $pid)"`);
  lines.push(`      kill "$pid" 2>/dev/null || true`);
  lines.push(`    fi`);
  lines.push(`  done`);
  lines.push(`  # Wait for all to exit`);
  lines.push(`  for name in "\${!DAEMON_PIDS[@]}"; do`);
  lines.push(`    wait "\${DAEMON_PIDS[$name]}" 2>/dev/null || true`);
  lines.push(`  done`);
  lines.push(`  log "supervisor" "All services stopped."`);
  lines.push(`  exit 0`);
  lines.push(`}`);
  lines.push(`trap cleanup SIGTERM SIGINT`);
  lines.push(``);

  // ── Preflight checks ────────────────────────────────────────────
  lines.push(`# ── Preflight checks ──`);
  for (const proj of instance.projects) {
    lines.push(`if [ -d "${proj.workspacePath}/node_modules" ] && ! [ -w "${proj.workspacePath}/node_modules" ]; then`);
    lines.push(`  log "preflight" "ERROR: ${proj.workspacePath}/node_modules is not writable by $(whoami). Fix host permissions or remove the volume."`);
    lines.push(`  exit 1`);
    lines.push(`fi`);
  }
  lines.push(``);

  // ── SSH key setup (if configured) ────────────────────────────────
  if (instance.ssh) {
    lines.push(`# ── SSH key setup ──`);
    lines.push(`if [ -f /home/coder/.ssh/id_key ]; then`);
    lines.push(`  log "preflight" "Setting up SSH key for git authentication"`);
    lines.push(``);
    lines.push(`  # Generate known_hosts for GitHub (and other common hosts)`);
    lines.push(`  ssh-keyscan -t ed25519,rsa github.com >> /home/coder/.ssh/known_hosts 2>/dev/null || true`);
    lines.push(`  chmod 644 /home/coder/.ssh/known_hosts`);
    lines.push(``);
    lines.push(`  # Create SSH config pointing to the mounted key`);
    lines.push(`  cat > /home/coder/.ssh/config << 'SSHEOF'`);
    lines.push(`Host github.com`);
    lines.push(`  HostName github.com`);
    lines.push(`  User git`);
    lines.push(`  IdentityFile /home/coder/.ssh/id_key`);
    lines.push(`  IdentitiesOnly yes`);
    lines.push(`  StrictHostKeyChecking accept-new`);
    lines.push(`SSHEOF`);
    lines.push(`  chmod 600 /home/coder/.ssh/config`);
    lines.push(``);
    lines.push(`  log "preflight" "SSH key configured successfully"`);
    lines.push(`else`);
    lines.push(`  log "preflight" "WARNING: SSH key mount expected but /home/coder/.ssh/id_key not found"`);
    lines.push(`fi`);
    lines.push(``);
  }

  // ── Clone/pull extra repositories ─────────────────────────────────
  if (instance.extraRepos.length > 0) {
    lines.push(`# ── Extra repositories (clone if missing, pull if present) ──`);
    for (const repoUrl of instance.extraRepos) {
      // Extract repo name from URL: https://github.com/org/repo.git → repo
      const repoName = repoUrl.replace(/\.git$/, "").split("/").pop() ?? "unknown";
      const targetDir = `/workspace/${repoName}`;
      lines.push(`if [ -d "${targetDir}/.git" ]; then`);
      lines.push(`  log "repos" "Pulling ${repoName}..."`);
      lines.push(`  (cd "${targetDir}" && GIT_TERMINAL_PROMPT=0 git pull --ff-only 2>&1 | sed "s/^/[repos:${repoName}] /") || log "repos" "Pull failed for ${repoName} (continuing)"`);
      lines.push(`elif [ ! -d "${targetDir}" ] || [ -z "$(ls -A "${targetDir}" 2>/dev/null)" ]; then`);
      lines.push(`  log "repos" "Cloning ${repoName}..."`);
      lines.push(`  (GIT_TERMINAL_PROMPT=0 git clone "${repoUrl}" "${targetDir}" 2>&1 | sed "s/^/[repos:${repoName}] /") || log "repos" "Clone failed for ${repoName} (continuing)"`);
      lines.push(`else`);
      lines.push(`  log "repos" "${repoName} exists but is not a git repo — skipping"`);
      lines.push(`fi`);
    }
    lines.push(``);
  }

  // ── Run a oneshot service ────────────────────────────────────────
  lines.push(`# ── Run oneshot service ──`);
  lines.push(`run_oneshot() {`);
  lines.push(`  local name="$1" cmd="$2" workdir="$3"`);
  lines.push(`  log "$name" "Running: $cmd (in $workdir)"`);
  lines.push(`  if (cd "$workdir" && eval "$cmd") 2>&1 | sed "s/^/[$name] /"; then`);
  lines.push(`    log "$name" "Completed successfully"`);
  lines.push(`  else`);
  lines.push(`    log "$name" "FAILED (exit $?)"`);
  lines.push(`    exit 1`);
  lines.push(`  fi`);
  lines.push(`}`);
  lines.push(``);

  // ── Start a daemon service ───────────────────────────────────────
  lines.push(`# ── Start daemon service ──`);
  lines.push(`start_daemon() {`);
  lines.push(`  local name="$1" cmd="$2" workdir="$3"`);
  lines.push(`  log "$name" "Starting: $cmd (in $workdir)"`);
  lines.push(`  (cd "$workdir" && eval "$cmd") 2>&1 | sed "s/^/[$name] /" &`);
  lines.push(`  DAEMON_PIDS[$name]=$!`);
  lines.push(`  RESTART_COUNTS[$name]=0`);
  lines.push(`  LAST_RESTART_TIMES[$name]=$(date +%s)`);
  lines.push(`  log "$name" "Started (PID \${DAEMON_PIDS[$name]})"`);
  lines.push(`}`);
  lines.push(``);

  // ── Restart a daemon with backoff ────────────────────────────────
  lines.push(`# ── Restart daemon with backoff ──`);
  lines.push(`restart_daemon() {`);
  lines.push(`  local name="$1" cmd="$2" workdir="$3" restart_policy="$4"`);
  lines.push(`  if [ "$restart_policy" = "never" ]; then`);
  lines.push(`    log "$name" "Exited. Restart policy is 'never', not restarting."`);
  lines.push(`    return`);
  lines.push(`  fi`);
  lines.push(`  local now=$(date +%s)`);
  lines.push(`  local last=\${LAST_RESTART_TIMES[$name]:-0}`);
  lines.push(`  local count=\${RESTART_COUNTS[$name]:-0}`);
  lines.push(`  if (( now - last < RAPID_WINDOW )); then`);
  lines.push(`    count=$((count + 1))`);
  lines.push(`  else`);
  lines.push(`    count=1`);
  lines.push(`  fi`);
  lines.push(`  RESTART_COUNTS[$name]=$count`);
  lines.push(`  LAST_RESTART_TIMES[$name]=$now`);
  lines.push(`  if (( count >= MAX_RAPID_RESTARTS )); then`);
  lines.push(`    log "$name" "Crashed $count times in ${RAPID_WINDOW}s — backing off ${BACKOFF_DELAY}s"`);
  lines.push(`    sleep "$BACKOFF_DELAY"`);
  lines.push(`    RESTART_COUNTS[$name]=0`);
  lines.push(`  else`);
  lines.push(`    sleep "$RESTART_DELAY"`);
  lines.push(`  fi`);
  lines.push(`  start_daemon "$name" "$cmd" "$workdir"`);
  lines.push(`}`);
  lines.push(``);

  // ── Run oneshot services (in dependency order) ───────────────────
  if (oneshots.length > 0) {
    lines.push(`# ── Oneshot services ──`);
    const sorted = topologicalSort(oneshots);
    for (const svc of sorted) {
      const workdir = svc.workdir ?? "/workspace";

      // For "bun install" / "npm install" oneshots, skip if deps are up to date
      const isInstallCmd = /\b(bun|npm|yarn|pnpm)\s+install\b/.test(svc.command);
      if (isInstallCmd) {
        lines.push(`# Conditional install — skip if node_modules looks up to date`);
        lines.push(`if [ ! -d "${workdir}/node_modules/.cache" ] || [ ! -f "${workdir}/node_modules/.package-lock.json" ]; then`);
      }

      if (svc.env && Object.keys(svc.env).length > 0) {
        const envExports = Object.entries(svc.env)
          .map(([k, v]) => `export ${k}="${escapeShell(v)}"`)
          .join("; ");
        lines.push(`  (${envExports}; run_oneshot "${svc.name}" "${escapeShell(svc.command)}" "${workdir}")`);
      } else {
        const indent = isInstallCmd ? "  " : "";
        lines.push(`${indent}run_oneshot "${svc.name}" "${escapeShell(svc.command)}" "${workdir}"`);
      }

      if (isInstallCmd) {
        lines.push(`else`);
        lines.push(`  log "${svc.name}" "node_modules looks up to date, skipping install"`);
        lines.push(`fi`);
      }
    }
    lines.push(``);
  }

  // ── Start daemon services ────────────────────────────────────────
  if (daemons.length > 0) {
    lines.push(`# ── Daemon services ──`);
    const sorted = topologicalSort(daemons);
    for (const svc of sorted) {
      const workdir = svc.workdir ?? "/workspace";
      if (svc.env && Object.keys(svc.env).length > 0) {
        // Wrap in subshell with env vars — inner quotes must be escaped
        // since the whole command string is already double-quoted
        const envPrefix = Object.entries(svc.env)
          .map(([k, v]) => `${k}=\\\"${escapeShell(v)}\\\"`)
          .join(" ");
        lines.push(`start_daemon "${svc.name}" "${envPrefix} ${escapeShell(svc.command)}" "${workdir}"`);
      } else {
        lines.push(`start_daemon "${svc.name}" "${escapeShell(svc.command)}" "${workdir}"`);
      }
      // Give services time to bind ports before starting the next one
      lines.push(`sleep 2`);
    }
    lines.push(``);
  }

  // ── Always start remote-opencode last ────────────────────────────
  lines.push(`# ── remote-opencode (Discord bridge — always last) ──`);
  lines.push(`start_daemon "remote-opencode" "remote-opencode start" "/workspace"`);
  lines.push(``);

  // ── Status output ────────────────────────────────────────────────
  lines.push(`# ── Startup complete ──`);
  lines.push(`log "supervisor" "All services running."`);
  lines.push(`log "supervisor" "Daemons:"`);
  lines.push(`for name in "\${!DAEMON_PIDS[@]}"; do`);
  lines.push(`  log "supervisor" "  $name (PID \${DAEMON_PIDS[$name]})"`);
  lines.push(`done`);
  lines.push(`log "supervisor" "Watchdog monitoring every \${WATCHDOG_INTERVAL}s"`);
  lines.push(``);

  // ── Watchdog loop ────────────────────────────────────────────────
  lines.push(`# ── Watchdog loop ──`);
  // Build a lookup of daemon commands and restart policies for the watchdog
  lines.push(`declare -A DAEMON_CMDS`);
  lines.push(`declare -A DAEMON_WORKDIRS`);
  lines.push(`declare -A DAEMON_RESTART`);
  for (const svc of daemons) {
    const workdir = svc.workdir ?? "/workspace";
    // Must include env prefix so watchdog restarts with the same env vars
    if (svc.env && Object.keys(svc.env).length > 0) {
      const envPrefix = Object.entries(svc.env)
        .map(([k, v]) => `${k}=\\\"${escapeShell(v)}\\\"`)
        .join(" ");
      lines.push(`DAEMON_CMDS["${svc.name}"]="${envPrefix} ${escapeShell(svc.command)}"`);
    } else {
      lines.push(`DAEMON_CMDS["${svc.name}"]="${escapeShell(svc.command)}"`);
    }
    lines.push(`DAEMON_WORKDIRS["${svc.name}"]="${workdir}"`);
    lines.push(`DAEMON_RESTART["${svc.name}"]="${svc.restart}"`);
  }
  // remote-opencode is always a daemon with restart=always
  lines.push(`DAEMON_CMDS["remote-opencode"]="remote-opencode start"`);
  lines.push(`DAEMON_WORKDIRS["remote-opencode"]="/workspace"`);
  lines.push(`DAEMON_RESTART["remote-opencode"]="always"`);
  lines.push(``);

  lines.push(`while true; do`);
  lines.push(`  sleep "$WATCHDOG_INTERVAL"`);
  lines.push(`  if $SHUTTING_DOWN; then break; fi`);
  lines.push(``);
  lines.push(`  for name in "\${!DAEMON_PIDS[@]}"; do`);
  lines.push(`    if ! kill -0 "\${DAEMON_PIDS[$name]}" 2>/dev/null; then`);
  lines.push(`      log "watchdog" "$name exited (was PID \${DAEMON_PIDS[$name]})"`);
  lines.push(`      restart_daemon "$name" "\${DAEMON_CMDS[$name]}" "\${DAEMON_WORKDIRS[$name]}" "\${DAEMON_RESTART[$name]}"`);
  lines.push(`    fi`);
  lines.push(`  done`);
  lines.push(`done`);

  return lines.join("\n") + "\n";
}

// ─── Helpers ───────────────────────────────────────────────────────────────

function escapeShell(s: string): string {
  // Escape double quotes and backslashes for embedding in bash double-quoted strings
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

interface Sortable {
  name: string;
  dependsOn?: string[];
}

function topologicalSort<T extends Sortable>(items: T[]): T[] {
  const byName = new Map<string, T>();
  for (const item of items) byName.set(item.name, item);

  const sorted: T[] = [];
  const visited = new Set<string>();
  const visiting = new Set<string>();

  function visit(name: string) {
    if (visited.has(name)) return;
    if (visiting.has(name)) {
      throw new Error(`Circular dependency detected involving: ${name}`);
    }
    visiting.add(name);
    const item = byName.get(name);
    if (item?.dependsOn) {
      for (const dep of item.dependsOn) {
        if (byName.has(dep)) visit(dep);
      }
    }
    visiting.delete(name);
    visited.add(name);
    if (item) sorted.push(item);
  }

  for (const item of items) visit(item.name);
  return sorted;
}
