import fs from "node:fs";
import path from "node:path";
import type { ProjectConfig } from "../types.ts";
import { CONTAINER_WORKSPACE } from "../constants.ts";

/**
 * Credential file path inside the container for a given project.
 */
function containerCredPath(projectName: string): string {
  return `/home/coder/.git-credentials/${projectName}`;
}

/**
 * Generate git credential files and gitconfig for per-project PAT support.
 *
 * Architecture:
 *   - Each project with a PAT gets a git-credential-store file
 *     (format: https://<PAT>@github.com)
 *   - A sandbox gitconfig uses [includeIf "gitdir:..."] to route
 *     credential lookups to the right file based on working directory
 *   - A default credential file is used as fallback for repos not
 *     matching any project path
 *
 * Security:
 *   - PATs are never exposed as env vars (except GH_TOKEN for gh CLI)
 *   - Credential files are 600 permissions, owned by coder
 *   - Git reads credentials on demand, not stored in memory
 */
export function generateGitCredentials(
  projects: ProjectConfig[],
  defaultPat: string | undefined,
  outputDir: string,
): void {
  const credDir = path.join(outputDir, "git-credentials");
  fs.mkdirSync(credDir, { recursive: true });

  const gitconfigLines: string[] = [
    "# Auto-generated by remote-opencode-sandbox",
    "# Per-project git credential routing via includeIf",
    "# DO NOT EDIT — regenerate with: sandbox build",
    "",
  ];

  // ── Default credential (fallback) ──────────────────────────────
  if (defaultPat) {
    const defaultCredFile = path.join(credDir, "default");
    fs.writeFileSync(defaultCredFile, `https://${defaultPat}@github.com\n`, {
      encoding: "utf-8",
      mode: 0o600,
    });

    gitconfigLines.push("# Fallback credential for repos not matching any project path");
    gitconfigLines.push("[credential]");
    gitconfigLines.push(`\thelper = store --file=${containerCredPath("default")}`);
    gitconfigLines.push("");
  }

  // ── Per-project credentials ────────────────────────────────────
  for (const proj of projects) {
    const pat = proj.githubPat === "default" ? defaultPat : proj.githubPat;
    if (!pat) continue;

    // Write credential file
    const credFile = path.join(credDir, proj.name);
    fs.writeFileSync(credFile, `https://${pat}@github.com\n`, {
      encoding: "utf-8",
      mode: 0o600,
    });

    // Write per-project gitconfig fragment
    const projGitconfig = path.join(credDir, `${proj.name}.gitconfig`);
    const projGitconfigContent = [
      `# Credentials for project: ${proj.name}`,
      "[credential]",
      `\thelper = store --file=${containerCredPath(proj.name)}`,
      "",
    ].join("\n");
    fs.writeFileSync(projGitconfig, projGitconfigContent, {
      encoding: "utf-8",
      mode: 0o600,
    });

    // Add includeIf directive to main gitconfig
    const workspacePath = `${CONTAINER_WORKSPACE}/${proj.name}/`;
    gitconfigLines.push(`# Project: ${proj.name}`);
    gitconfigLines.push(`[includeIf "gitdir:${workspacePath}"]`);
    gitconfigLines.push(`\tpath = ${containerCredPath(proj.name)}.gitconfig`);
    gitconfigLines.push("");
  }

  // Write the main gitconfig fragment
  const gitconfigFile = path.join(credDir, "gitconfig.sandbox");
  fs.writeFileSync(gitconfigFile, gitconfigLines.join("\n") + "\n", {
    encoding: "utf-8",
    mode: 0o600,
  });
}
